version: "3"

services:
  pgsql:
    image: postgres:11.2-alpine
    restart: always
    container_name: test_pgsql
    ports:
      - "65433:5432"
    environment:
        - POSTGRES_PASSWORD=business
        - POSTGRES_DB=business
        - POSTGRES_USER=business
        - TZ=Asia/Shanghai
    volumes:
      - /var/postgresql:/var/postgresql/data


  phadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8001:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=1234@qq.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    volumes:
      - /var/pgadmin:/var/pgadmin/data


