version: "3"

services:
  pgsql:
    image: postgres:11.2-alpine
    restart: always
    container_name: test_pgsql
    ports:
      - "65433:5432"
    environment:
        - POSTGRES_PASSWORD=business
        - POSTGRES_DB=business
        - POSTGRES_USER=business
        - TZ=Asia/Shanghai
    volumes:
      - /var/postgresql:/var/postgresql/data
  zoo1:
    image: wurstmeister/zookeeper
    restart: unless-stopped
    hostname: zoo1
    ports:
      - "2181:2181"
    container_name: zookeeper

  kafka1:
      image: wurstmeister/kafka
      ports:
        - "9092:9092"
      environment:
        KAFKA_ADVERTISED_HOST_NAME: 192.168.31.180                     ## 修改:宿主机IP
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.31.180:9092    ## 修改:宿主机IP
        KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
        KAFKA_ADVERTISED_PORT: 9092
        KAFKA_BROKER_ID: 1
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      depends_on:
        - zoo1
      container_name: kafka1

  kafka2:
      image: wurstmeister/kafka
      ports:
        - "9093:9092"
      environment:
        KAFKA_ADVERTISED_HOST_NAME: 192.168.31.180                    ## 修改:宿主机IP
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.31.180:9093   ## 修改:宿主机IP
        KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
        KAFKA_ADVERTISED_PORT: 9093
        KAFKA_BROKER_ID: 2
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      depends_on:
        - zoo1
      container_name: kafka2

  kafka-manager:
      image: sheepkiller/kafka-manager              ## 镜像：开源的web管理kafka集群的界面
      environment:
        ZK_HOSTS: 192.168.31.180                   ## 修改:宿主机IP
      ports:
        - "9000:9000"                               ## 暴露端口

  phadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8001:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=824426699@qq.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    volumes:
      - /var/pgadmin:/var/pgadmin/data


  redis:
    image: redis
    container_name: redis
    restart: always
    volumes:
      - /var/redis/data:/data/redis
      - /var/redis/redis.conf:/etc/redis/redis.conf
      - /var/redis/log:/var/log/redis
#    environment:
#      - REDIS_PASSWORD=business
    command: redis-server  /etc/redis/redis.conf
    ports:
    - "6379:6379"


        
