version: "3"

services:
  db:
    image: "mysql:5.7"
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "test_db"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "123456"
    container_name: db_one
    ports:
      - "3306:3306"
  db_admin:
    image: adminer
    ports:
    - 3006:8080
    depends_on:
      - db
  mq:
    image: webcenter/activemq:latest
    ports:
    - 61616:61616
    - 8161:8161
